version: '2'
services:
  web:
    container_name: deck_ms
    build: ./
    links:
      - db
    ports:
      - 4005:4005
    depends_on:
      - db
  db:
    container_name: deck_db
    image: mongo
    command: mongod --port 27020
    expose:
      - "27020"
    volumes:
        - mongodata:/data/db

volumes:
  mongodata:


# app:
#   build: ./
  # depends_on:
  #   - db
#   ports:
#     - 8888:8888
  
#   environment:
#     - NODE_ENV=development
#     - PORT=8888
# db: 
#   image: mongo
#   expose:
#     - "27017"
#   volumes:
#     mongodata:/data/db   

# volumes:
#   mongodata: